title: THE QUEEN KNOWS IT ALL BLOG!
author: MONIQUE BASS  
email:NIKABABY01@GMAIL.com
description: The Hottest Site for Entertainment News featuring your favorite Celebrities.

# social links
twitter_username: Mrs_Bass
github_username:  Nikbaby01

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
